version: '3.8'

services:
  banksimulator-blazor:
    image: mycompanyname/banksimulator-blazor:latest
    container_name: banksimulator-blazor
    build:
      context: ../../
      dockerfile: src/BankSimulator.Blazor/Dockerfile.local
    ports:
      - "44307:80"
    depends_on:
      - banksimulator-api
    restart: on-failure
    volumes:
      - ./appsettings.json:/usr/share/nginx/html/appsettings.json
    networks:
      - abp-network

  banksimulator-api:
    image: mycompanyname/banksimulator-api:latest
    container_name: banksimulator-api
    hostname: banksimulator-api
    build:
      context: ../../
      dockerfile: src/BankSimulator.HttpApi.Host/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__SelfUrl=https://localhost:44354
      - App__CorsOrigins=http://localhost:44307
      - App__HealthCheckUrl=http://banksimulator-api/health-status
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://banksimulator-api
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=BankSimulator;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    ports:
      - "44354:443"
    depends_on:
      sql-server:
        condition: service_healthy
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network
  


  db-migrator:
    image: mycompanyname/banksimulator-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/BankSimulator.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__BankSimulator_Blazor__RootUrl=http://localhost:44307
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=BankSimulator;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network    
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network  
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
volumes:
  sqldata:
    name: banksimulator_sqldata
networks:
  abp-network:
    name: banksimulator-network
    driver: bridge